# Generated by Django 6.0.1 on 2026-09-02 12:20

import accounts.utils
import django.db.models.deletion
import rh.models.tarefas_trabalhistas.tarefa
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_empresagrupoeconomico'),
        ('rh', '0028_planejamento_ia_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTrabalhista',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FALTA_ASSUMIR', 'Falta assumir'), ('EXECUTANDO', 'Executando'), ('VALIDAR', 'Validar'), ('FINALIZADA', 'Finalizada')], default='FALTA_ASSUMIR', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_trabalhistas', to='cliente.clientemodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_trabalhistas_assumidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_sugerido', models.ForeignKey(blank=True, help_text='Sugestão de quem deve assumir, indicada por quem criou. Não atribui automaticamente — só destaca na notificação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_trabalhistas_sugeridas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa Trabalhista',
                'verbose_name_plural': 'Tarefas Trabalhistas',
                'db_table': 'rh_tarefa_trabalhista',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAnexo',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to=rh.models.tarefas_trabalhistas.tarefa.tarefa_anexo_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='rh.tarefatrabalhista')),
            ],
            options={
                'verbose_name': 'Anexo da Tarefa Trabalhista',
                'verbose_name_plural': 'Anexos da Tarefa Trabalhista',
                'db_table': 'rh_tarefa_trabalhista_anexo',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarefaTrabalhistaAcaoPermitida',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('ASSISTENTE', 'Assistente'), ('ANALISTA_JR', 'Analista Jr'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('GERENCIA', 'Gerência'), ('DESENVOLVEDOR', 'Desenvolvedor')], max_length=20)),
                ('acao', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação permitida por nível (Tarefas Trabalhistas)',
                'verbose_name_plural': 'Ações permitidas por nível (Tarefas Trabalhistas)',
                'db_table': 'rh_tarefa_trabalhista_acao_permitida',
            },
        ),
        migrations.CreateModel(
            name='TarefaTrabalhistaAcesso',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('ASSISTENTE', 'Assistente'), ('ANALISTA_JR', 'Analista Jr'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('GERENCIA', 'Gerência'), ('DESENVOLVEDOR', 'Desenvolvedor')], default='ASSISTENTE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso_tarefas_trabalhistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à Esteira de Tarefas Trabalhistas',
                'verbose_name_plural': 'Acessos à Esteira de Tarefas Trabalhistas',
                'db_table': 'rh_tarefa_trabalhista_acesso',
            },
        ),
        migrations.CreateModel(
            name='TarefaTrabalhistaEvento',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('de_status', models.CharField(blank=True, default='', max_length=20)),
                ('para_status', models.CharField(choices=[('FALTA_ASSUMIR', 'Falta assumir'), ('EXECUTANDO', 'Executando'), ('VALIDAR', 'Validar'), ('FINALIZADA', 'Finalizada')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='rh.tarefatrabalhista')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento da Tarefa Trabalhista',
                'verbose_name_plural': 'Eventos da Tarefa Trabalhista',
                'db_table': 'rh_tarefa_trabalhista_evento',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefatrabalhista',
            index=models.Index(fields=['status'], name='idx_tarefa_trab_status'),
        ),
        migrations.AddConstraint(
            model_name='tarefatrabalhistaacaopermitida',
            constraint=models.UniqueConstraint(fields=('nivel', 'acao'), name='uq_tarefa_nivel_acao'),
        ),
    ]
