# Generated by Django 6.0.1 on 2026-09-02 13:39

import accounts.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_tarefatrabalhista_tarefaanexo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaComentario',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='rh.tarefatrabalhista')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário da Tarefa Trabalhista',
                'verbose_name_plural': 'Comentários da Tarefa Trabalhista',
                'db_table': 'rh_tarefa_trabalhista_comentario',
                'ordering': ['created_at'],
            },
        ),
    ]
