# Generated by Django 6.0.1 on 2026-09-02 14:13

import accounts.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_tarefacomentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTrabalhistaLog',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarefa_id', models.CharField(db_index=True, max_length=30)),
                ('tarefa_titulo', models.CharField(max_length=255)),
                ('acao', models.CharField(choices=[('criada', 'Criada'), ('assumida', 'Assumida'), ('enviada_validacao', 'Enviada para validação'), ('validada', 'Validada / Concluída'), ('reprovada', 'Reprovada'), ('excluida', 'Excluída'), ('anexo_adicionado', 'Anexo adicionado'), ('anexo_removido', 'Anexo removido'), ('comentario', 'Comentário')], max_length=30)),
                ('detalhes', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log da Tarefa Trabalhista',
                'verbose_name_plural': 'Logs da Tarefa Trabalhista',
                'db_table': 'rh_tarefa_trabalhista_log',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tarefa_id', 'created_at'], name='idx_tt_log_tarefa_criado')],
            },
        ),
    ]
