# Generated by Django 6.0.1 on 2026-09-02 14:45

import accounts.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_tarefatrabalhistalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatrabalhistalog',
            name='acao',
            field=models.CharField(choices=[('criada', 'Criada'), ('assumida', 'Assumida'), ('enviada_validacao', 'Enviada para validação'), ('validada', 'Validada / Concluída'), ('reprovada', 'Reprovada'), ('excluida', 'Excluída'), ('anexo_adicionado', 'Anexo adicionado'), ('anexo_removido', 'Anexo removido'), ('comentario', 'Comentário'), ('checklist_adicionado', 'Item de checklist adicionado'), ('checklist_atualizado', 'Item de checklist marcado/desmarcado'), ('checklist_removido', 'Item de checklist removido')], max_length=30),
        ),
        migrations.CreateModel(
            name='TarefaChecklistItem',
            fields=[
                ('idmaster', models.CharField(default=accounts.utils.gerarIdMaster, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='rh.tarefatrabalhista')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Checklist da Tarefa Trabalhista',
                'verbose_name_plural': 'Itens de Checklist da Tarefa Trabalhista',
                'db_table': 'rh_tarefa_trabalhista_checklist_item',
                'ordering': ['created_at'],
            },
        ),
    ]
