# Generated by Django 6.0.7 on 2026-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_alter_tarefatrabalhistalog_acao_tarefachecklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatrabalhistalog',
            name='acao',
            field=models.CharField(choices=[('criada', 'Criada'), ('assumida', 'Assumida'), ('enviada_validacao', 'Enviada para validação'), ('validada', 'Validada / Concluída'), ('reprovada', 'Reprovada'), ('excluida', 'Excluída'), ('anexo_adicionado', 'Anexo adicionado'), ('anexo_removido', 'Anexo removido'), ('comentario', 'Comentário'), ('checklist_adicionado', 'Item de checklist adicionado'), ('checklist_atualizado', 'Item de checklist marcado/desmarcado'), ('checklist_removido', 'Item de checklist removido'), ('movida_livre', 'Movida livremente')], max_length=30),
        ),
    ]
