# Generated by Django 6.0.7 on 2026-09-02 19:55

import rh.models.tarefas_trabalhistas.tarefa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0033_alter_tarefatrabalhistalog_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefacomentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=rh.models.tarefas_trabalhistas.tarefa.tarefa_comentario_imagem_path),
        ),
        migrations.AddField(
            model_name='tarefatrabalhista',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='tarefatrabalhistaacesso',
            name='notificar_criacao_email',
            field=models.BooleanField(default=False, help_text='Recebe e-mail (não só Teams) sempre que uma tarefa nova é criada na esteira. Lista editável na própria tela de Permissões.'),
        ),
        migrations.AlterField(
            model_name='tarefacomentario',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tarefatrabalhistalog',
            name='acao',
            field=models.CharField(choices=[('criada', 'Criada'), ('assumida', 'Assumida'), ('enviada_validacao', 'Enviada para validação'), ('validada', 'Validada / Concluída'), ('reprovada', 'Reprovada'), ('excluida', 'Excluída'), ('anexo_adicionado', 'Anexo adicionado'), ('anexo_removido', 'Anexo removido'), ('comentario', 'Comentário'), ('checklist_adicionado', 'Item de checklist adicionado'), ('checklist_atualizado', 'Item de checklist marcado/desmarcado'), ('checklist_removido', 'Item de checklist removido'), ('movida_livre', 'Movida livremente'), ('prioridade_alterada', 'Prioridade alterada'), ('lembrete_prazo', 'Lembrete de prazo próximo enviado'), ('lembrete_atrasada', 'Aviso de atraso enviado ao criador')], max_length=30),
        ),
    ]
